#!bin/bash

nmcli con mod ens192 ipv4.addresses 192.168.1.113/24
nmcli con mod ens192 ipv4.gateway 192.168.1.254
nmcli con mod ens192 ipv4.method manual
nmcli con mod ens192 ipv4.dns "8.8.8.8"
sudo nmcli general hostname IDX1
nmcli con up ens192
cd /opt
sudo wget -O splunk-8.2.2-87344edfcdb4-Linux-x86_64.tgz 'https://d7wz6hmoaavd0.cloudfront.net/products/splunk/releases/8.2.2/linux/splunk-8.2.2-87344edfcdb4-Linux-x86_64.tgz' && sudo tar -xf splunk-8.2.2-87344edfcdb4-Linux-x86_64.tgz
sudo chown -R splunk:splunk /opt/splunk
cd splunk/bin && ./splunk enable boot-start -user splunk -systemd-managed 1 --accept-license
sudo systemctl start Splunkd.service
sleep 1m
./splunk enable listen 9997
./splunk edit cluster-config -mode slave -master_uri https://192.168.1.112:8089 -secret clusterbuster1234 -replication_port 9100
sudo firewall-cmd --zone=public --permanent --add-port 8000/tcp
sudo firewall-cmd --zone=public --permanent --add-port 8089/tcp
sudo firewall-cmd --reload
sudo firewall-cmd --list-all
sudo reboot
